spring.application.name=MilkyWay

server.port=8990
#ViewResolver:To identify presentation file location and presentation Technology 
#prefix: Location
#suffix: .extension of UI(View)
#spring.mvc.view.prefix=/Views/
#spring.mvc.view.suffix=.jsp

##Connection details

#DriverManager(Fully qualified name of the JDBC driver). Auto-detected based on the URL by default.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JDBC URL of the Database
spring.datasource.url=jdbc:mysql://localhost:3306/MilkyWay?createDatabaseIfNotExist=true

#Login username of the database.
spring.datasource.username=root

#Login password of the database.
spring.datasource.password=HBSY@09

#Print the query on the console
spring.jpa.show-sql=true

#Table is not available then create a table(create), after update
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.format_sql=true

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=harsharajbsy@gmail.com
#spring.mail.password=iuog kueh akux shtd
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
#cloudinary.cloud_name=daoog1zxo
#cloudinary.api_key=995888764497144
#cloudinary.api_secret=CCLoKn69bNtXLw5NPMPjWWgbc98
